### PR TITLE
fix(connector): Realize the HTTP response before closing the stream. …

### LINKED ISSUE #2607: Http connector throws when trying to get response
**Describe the bug**

Starting with version 1.1.0, I get the following error when trying to access the response of the http request from an http connector:

```
Unexpected exception thrown: org.operaton.connect.ConnectorResponseException: HTCL-02004 Unable to read connectorResponse: Stream already closed
        at org.junit.jupiter.api.AssertionFailureBuilder.build(AssertionFailureBuilder.java:152)
        at org.junit.jupiter.api.AssertDoesNotThrow.createAssertionFailedError(AssertDoesNotThrow.java:84)
        at org.junit.jupiter.api.AssertDoesNotThrow.assertDoesNotThrow(AssertDoesNotThrow.java:75)
        at org.junit.jupiter.api.AssertDoesNotThrow.assertDoesNotThrow(AssertDoesNotThrow.java:58)
        at org.junit.jupiter.api.Assertions.assertDoesNotThrow(Assertions.java:3259)
        at repro.HttpConnectorReproTest. httpConnector_getRequest_shouldHaveReadableResponse(HttpConnectorReproTest.java:24)
        at java.base/java.lang.reflect.Method.invoke(Method.java:569)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
Caused by: org.operaton.connect.ConnectorResponseException: HTCL-02004 Unable to read connectorResponse: Stream already closed
        at org.operaton.connect.httpclient.impl.HttpConnectorLogger.unableToReadResponse(HttpConnectorLogger.java:40)
        at org.operaton.connect.httpclient.impl.HttpResponseImpl.collectResponseParameters(HttpResponseImpl.java:76)
        at org.operaton.connect.impl.AbstractConnectorResponse.getResponseParameters(AbstractConnectorResponse.java:36)
        at org.operaton.connect.impl.AbstractConnectorResponse.getResponseParameter(AbstractConnectorResponse.java:44)
        at org.operaton.connect.httpclient.impl.HttpResponseImpl.getResponse(HttpResponseImpl.java:48)
        at repro.HttpConnectorReproTest.lambda$httpConnector_getRequest_shouldHaveReadableResponse $0(HttpConnectorReproTest.java:24)
        at org.junit.jupiter.api.AssertDoesNotThrow.assertDoesNotThrow(AssertDoesNotThrow.java:71)
        ... 6 more
Caused by: connectjar.org.apache.hc.core5.http.StreamClosedException: Stream already closed
        at connectjar.org.apache.hc.core5.http.impl.io.ContentLengthInputStream.read(ContentLengthInputStream.java:162)
        at connectjar.org.apache.hc.core5.http.io.EofSensorInputStream.read(EofSensorInputStream.java:138)
        at java.base/java.io.InputStream.readNBytes(InputStream.java:409)
        at java.base/java.io.InputStream.readAllBytes(InputStream.java:346)
        at org.operaton.connect.httpclient.impl.HttpResponseImpl.collectResponseParameters(HttpResponseImpl.java:73)
        ... 11 more
```

When downgrading to version 1.0.3, everything works as expected (=> no error).

**To Reproduce**

While I first saw this error when running it via a workflow, I was able to reproduce it by directly using the `HttpConnectorImpl` with the following, very simple test:

```java
@Test
void httpConnector_getRequest_shouldHaveReadableResponse() {
  HttpConnectorImpl connector = new HttpConnectorImpl();

  HttpRequest request = connector.createRequest();
  request.setRequestParameter("method", "GET");
  request.setRequestParameter("url", "https://httpbin.org/get");

  HttpResponse response = request.execute();

  assertDoesNotThrow(() -> response.getResponse());
}
```

### PR DESCRIPTION
**Pull request by javahippie**
…Fix possible memory leak

Fixes #2607

### CODE REVIEW

File: commons/utils/src/main/java/org/operaton/commons/utils/IoUtil.java [hunk 1]
```diff
@@ -49,7 +49,7 @@ public static String inputStreamAsString(InputStream inputStream) {
    * @return the input stream as byte[].
    */
   public static byte[] inputStreamAsByteArray(InputStream inputStream) {
-    try {
+    try (inputStream) {
```
Comment (javahippie) [inline commons/utils/src/main/java/org/operaton/commons/utils/IoUtil.java:52]: Restored try-with-resource pattern again, to prevent memory leaks

File: connect/http-client/src/main/java/org/operaton/connect/httpclient/impl/HttpResponseImpl.java [hunk 2]
```diff
@@ -70,7 +71,7 @@ protected void collectResponseParameters(Map<String, Object> responseParameters)
 
     if (httpResponse.getEntity() != null) {
       try {
-        String response = new String(httpResponse.getEntity().getContent().readAllBytes());
+        String response = new String(httpResponse.getEntity().getContent().readAllBytes(), StandardCharsets.UTF_8);
```
Comment (javahippie) [inline connect/http-client/src/main/java/org/operaton/connect/httpclient/impl/HttpResponseImpl.java:74]: The old http connector logic defaulted to UTF-8, this change made the connector use the platform encoding ,which could be different.

@kthoms might be sensible to make this customizable in the future, maybe?

**Comment by javahippie** [comment]
I verified that the unit test failed before changing anything else, so it is a working reproducer for the described bug

**Comment by javahippie** [comment]
Integration test run: https://github.com/operaton/operaton/actions/runs/23286894709

Edit: Succeeded

File: commons/utils/src/main/java/org/operaton/commons/utils/IoUtil.java (hunk 1 above)
Comment (kthoms) [reply commons/utils/src/main/java/org/operaton/commons/utils/IoUtil.java:52]: ok

File: connect/http-client/src/main/java/org/operaton/connect/httpclient/impl/HttpResponseImpl.java (hunk 2 above)
Comment (kthoms) [reply connect/http-client/src/main/java/org/operaton/connect/httpclient/impl/HttpResponseImpl.java:74]: Opened https://github.com/operaton/operaton/issues/2613

**Review by kthoms — APPROVED** [review]
I have verified that the test reproduces the issue and that the change fixes it. Good that this is fixed. I'll cherry-pick to release/1.1.x
