### PR TITLE
Fix Integration test execution with Postgres on Wildfly

### LINKED ISSUE #651: Fix integration tests wildfly,postgres
**Describe the bug**
The engine integration tests for wildfly,postgres [are failing with error](https://github.com/operaton/operaton/actions/runs/14032002825/job/39281479028).

```
Error:    TestProcessEnginesXmlInProcessApplication » Deployment Cannot deploy test.war: {"WFLYCTL0062: Composite operation failed and was rolled back. Steps that failed:" => {"Operation step-1" => {"WFLYCTL0080: Failed services" => {"org.operaton.bpm.platform.process-engine.engine1" => "org.operaton.bpm.engine.ProcessEngineException: ENGINE-12012 Exception on accessing the database connection: jakarta.resource.ResourceException: IJ000453: Unable to get managed connection for java:jboss/datasources/ProcessEngine
    Caused by: org.operaton.bpm.engine.ProcessEngineException: ENGINE-12012 Exception on accessing the database connection: jakarta.resource.ResourceException: IJ000453: Unable to get managed connection for java:jboss/datasources/ProcessEngine
    Caused by: java.sql.SQLException: jakarta.resource.ResourceException: IJ000453: Unable to get managed connection for java:jboss/datasources/ProcessEngine
    Caused by: jakarta.resource.ResourceException: IJ000453: Unable to get managed connection for java:jboss/datasources/ProcessEngine
    Caused by: jakarta.resource.ResourceException: IJ031084: Unable to create connection
    Caused by: jakarta.resource.ResourceException: IJ031083: Wrong driver class [org.postgresql.Driver] for this connection URL [jdbc:tc:operatonpostgresql:13.2:////TC_DAEMON=true]"}}}}
Error:    MigrationContextSwitchBeansTest » Deployment Cannot deploy client.war: WFLYCTL0063: Composite operation was rolled back
Error:    MigrationContextSwitchClassesTest » Deployment Cannot deploy client.war: WFLYCTL0063: Composite operation was rolled back
Error:    ModificationContextSwitchTest » Deployment Cannot deploy client.war: WFLYCTL0063: Composite operation was rolled back
Error:    FreeMarkerScriptEngineSupportTest » Deployment Cannot deploy test.war: WFLYCTL0063: Composite operation was rolled back
Error:    GroovyAsyncScriptExecutionTest>AbstractFoxPlatformIntegrationTest.setupBeforeTest:92 » NullPointer
Error:    GroovyPaClassImportTest » Deployment Cannot deploy pa1.war: WFLYCTL0063: Composite operation was rolled back
Error:    GroovyScriptEngineSupportTest » Deployment Cannot deploy test.war: WFLYCTL0063: Composite operation was rolled back
Error:    JavascriptScriptEngineSupportGraalJsTest » Deployment Cannot deploy test.war: WFLYCTL0063: Composite operation was rolled back
Error:    JavascriptScriptEngineSupportTest » Deployment Cannot deploy test.war: WFLYCTL0063: Composite operation was rolled back
Error:    OperatonScriptResourceTest » Deployment Cannot deploy test.war: WFLYCTL0063: Composite operation was rolled back
Error:    PaLocalScriptEngineCallActivityConditionTest » Deployment Cannot deploy pa1.war: WFLYCTL0063: Composite operation was rolled back
Error:    PaLocalScriptEngineDisabledCacheTest » Deployment Cannot deploy test.war: WFLYCTL0063: Composite operation was rolled back
...
```

**To Reproduce**
```
.devenv/scripts/build/build-and-run-integration-tests.sh --distro=wildfly --db=postgresql
```

**Expected behavior**
Build is successful.

### PR DESCRIPTION
**Pull request by javahippie**
Fixes the integration test execution with Postgres on Wildfly

Adds new utility classes (ArquillianLifecycleObserverExtension and ArquillianEventObserver) to manage test container lifecycle events. Start databases with Testcontainers before startup of the Wildfly container.

Updates event literal classes in engine-cdi to remove the abstract class dependency and directly extend AnnotationLiteral.

Fixes #651

### CODE REVIEW

File: qa/integration-tests-engine/src/test/java/org/operaton/bpm/integrationtest/util/ArquillianLifecycleObserverExtension.java [hunk 1]
```diff
@@ -0,0 +1,15 @@
+package org.operaton.bpm.integrationtest.util;
```
Comment (javahippie) [inline qa/integration-tests-engine/src/test/java/org/operaton/bpm/integrationtest/util/ArquillianLifecycleObserverExtension.java:1]: Lease add a license header

File: qa/integration-tests-engine/src/test/java/org/operaton/bpm/integrationtest/util/DeploymentHelper.java [hunk 2]
```diff
@@ -29,6 +29,8 @@ public class DeploymentHelper extends AbstractDeploymentHelper {
   protected static final String OPERATON_ENGINE = "org.operaton.bpm:operaton-engine";
   protected static JavaArchive cachedAssertJ;
 
+  protected static JavaArchive chachedTestcontainers;
```
Comment (javahippie) [inline qa/integration-tests-engine/src/test/java/org/operaton/bpm/integrationtest/util/DeploymentHelper.java:32]: Leftover from an experiment, can be removed

File: qa/wildfly-runtime/src/main/common/standalone/deployments/postgresql-ds.xml [hunk 3]
```diff
@@ -17,8 +18,8 @@
       <flush-strategy>FailingConnectionOnly</flush-strategy>
     </pool>
     <security>
-      <user-name>${database.username}</user-name>
-      <password>${database.password}</password>
+      <user-name>test</user-name>
```
Comment (javahippie) [inline qa/wildfly-runtime/src/main/common/standalone/deployments/postgresql-ds.xml:21]: Make user and password dynamic, too

Comment (WoSchmo) [reply qa/wildfly-runtime/src/main/common/standalone/deployments/postgresql-ds.xml:21]: Where/How would the values for the variables be provided?

Comment (javahippie) [reply qa/wildfly-runtime/src/main/common/standalone/deployments/postgresql-ds.xml:21]: Passed as JVM Args in `ArquillianEventObserver` line 65

File: qa/integration-tests-engine/src/test/java/org/operaton/bpm/integrationtest/util/ArquillianEventObserver.java [hunk 4]
```diff
@@ -0,0 +1,70 @@
...
+     * @param serviceLoader arquillian server loader
+     */
+    public void onContainerRegistryEvent(@Observes ContainerRegistry registry, ServiceLoader serviceLoader) {
+        var containerName = System.getProperty("databaseType");
+
+        if(containerName != null && AVAILABLE_DB_CONTAINERS.containsKey(containerName)) {
+            dbContainer = AVAILABLE_DB_CONTAINERS.get(containerName);
+            dbContainer.start();
+            dbContainer.waitingFor(CONTAINER_WAIT_STRATEGIES.get(containerName));
+            //Assume that there is only one container in the registry
```
[the remark this answers is not in the document]
Comment (kthoms) [reply qa/integration-tests-engine/src/test/java/org/operaton/bpm/integrationtest/util/ArquillianEventObserver.java:66]: @WoSchmo removed it

**Review by kthoms — APPROVED** [review]
Integration tests are working.
Polished the code.
