### PR TITLE
Start using Oracle Testcontainer [#553]

### LINKED ISSUE #569: Not able to select all tables for Oracle Database
**Describe the bug**
When trying to run integration tests with Oracle Database, the following exception occurs:

```
org.operaton.bpm.engine.ProcessEngineException: ENGINE-03019 Unable to fetch process engine table names.

	at org.operaton.bpm.engine.impl.db.EnginePersistenceLogger.getDatabaseTableNameException(EnginePersistenceLogger.java:247)
	at org.operaton.bpm.engine.impl.db.sql.DbSqlSession.getTableNamesPresent(DbSqlSession.java:648)
	at org.operaton.bpm.engine.impl.db.entitymanager.DbEntityManager.getTableNamesPresentInDatabase(DbEntityManager.java:749)
	at org.operaton.bpm.engine.impl.cmd.PurgeDatabaseAndCacheCmd.purgeDatabase(PurgeDatabaseAndCacheCmd.java:79)
	at org.operaton.bpm.engine.impl.cmd.PurgeDatabaseAndCacheCmd.execute(PurgeDatabaseAndCacheCmd.java:62)
	at org.operaton.bpm.engine.impl.cmd.PurgeDatabaseAndCacheCmd.execute(PurgeDatabaseAndCacheCmd.java:45)
	at org.operaton.bpm.engine.impl.interceptor.CommandExecutorImpl.execute(CommandExecutorImpl.java:29)
	at org.operaton.bpm.engine.impl.interceptor.CommandContextInterceptor.execute(CommandContextInterceptor.java:113)
	at org.operaton.bpm.engine.impl.interceptor.ProcessApplicationContextInterceptor.execute(ProcessApplicationContextInterceptor.java:64)
	at org.operaton.bpm.engine.impl.interceptor.CommandCounterInterceptor.execute(CommandCounterInterceptor.java:34)
	at org.operaton.bpm.engine.impl.interceptor.LogInterceptor.execute(LogInterceptor.java:34)
	at org.operaton.bpm.engine.impl.interceptor.ExceptionCodeInterceptor.execute(ExceptionCodeInterceptor.java:55)
	at org.operaton.bpm.engine.impl.ManagementServiceImpl.purge(ManagementServiceImpl.java:294)
	at org.operaton.bpm.engine.impl.test.TestHelper.assertAndEnsureCleanDbAndCache(TestHelper.java:359)
	at org.operaton.bpm.engine.impl.test.TestHelper.assertAndEnsureCleanDbAndCache(TestHelper.java:340)
	at org.operaton.bpm.engine.test.junit5.ProcessEngineExtension.afterTestExecution(ProcessEngineExtension.java:261)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
Caused by: java.sql.SQLException: ORA-17041: Fehlender IN- oder OUT-Parameter auf Index: 1
https://docs.oracle.com/error-help/db/ora-17041/
	at oracle.jdbc.driver.OraclePreparedStatement.processCompletedBindRow(OraclePreparedStatement.java:2067)
	at oracle.jdbc.driver.OraclePreparedStatement.executeInternal(OraclePreparedStatement.java:3940)
	at oracle.jdbc.driver.OraclePreparedStatement.executeQuery(OraclePreparedStatement.java:4142)
	at oracle.jdbc.driver.OraclePreparedStatementWrapper.executeQuery(OraclePreparedStatementWrapper.java:1103)
	at org.operaton.bpm.engine.impl.db.sql.DbSqlSession.getTablesPresentInOracleDatabase(DbSqlSession.java:661)
	at org.operaton.bpm.engine.impl.db.sql.DbSqlSession.getTableNamesPresent(DbSqlSession.java:614)
	... 16 more

```

**To Reproduce**
Check out branch `feature/enable-oracle-testcontainers` and run `mvn clean install -Pdistro,oracle` or start the engine with a connection to Oracle DB

The issue was probably introduced in a refactoring with PR #493. After the refactoring the statement is executed and the parameter is set afterwards, leading to the aforementioned error

### PR DESCRIPTION
**Pull request by javahippie**
Fixes #569
Relates to #553

### CODE REVIEW

File: test-utils/testcontainers/src/main/java/org/operaton/impl/test/utils/testcontainers/OperatonOracleContainerProvider.java [hunk 1]
```diff
@@ -0,0 +1,42 @@
...
+  private static final String NAME = "operatonoracle";
+
+  @Override
+  public boolean supports(String databaseType) {
+    return NAME.equals(databaseType);
+  }
+
+  @Override
+  public JdbcDatabaseContainer<?> newInstance(String tag) {
+    if("aaarch64".equals(System.getProperty("os.arch"))) {
```
Comment (kthoms) [inline test-utils/testcontainers/src/main/java/org/operaton/impl/test/utils/testcontainers/OperatonOracleContainerProvider.java:35]: Are there constants that could be used?

**Review by kthoms — APPROVED** [review]
